<?xml version="1.0"?>
<!DOCTYPE mame [
        <!ELEMENT mame (machine+)>
        <!ATTLIST mame build CDATA #IMPLIED>
        <!ATTLIST mame debug (yes|no) "no">
        <!ATTLIST mame mameconfig CDATA #REQUIRED>
        <!ELEMENT machine (description, year?, manufacturer?, biosset*, rom*, disk*, device_ref*, sample*, chip*, display*, sound?, input?, dipswitch*, configuration*, port*, adjuster*, driver?, device*, slot*, softwarelist*, ramoption*)>
        <!ATTLIST machine name CDATA #REQUIRED>
        <!ATTLIST machine sourcefile CDATA #IMPLIED>
        <!ATTLIST machine isbios (yes|no) "no">
        <!ATTLIST machine isdevice (yes|no) "no">
        <!ATTLIST machine ismechanical (yes|no) "no">
        <!ATTLIST machine runnable (yes|no) "yes">
        <!ATTLIST machine cloneof CDATA #IMPLIED>
        <!ATTLIST machine romof CDATA #IMPLIED>
        <!ATTLIST machine sampleof CDATA #IMPLIED>
        <!ELEMENT description (#PCDATA)>
        <!ELEMENT year (#PCDATA)>
        <!ELEMENT manufacturer (#PCDATA)>
        <!ELEMENT biosset EMPTY>
        <!ATTLIST biosset name CDATA #REQUIRED>
        <!ATTLIST biosset description CDATA #REQUIRED>
        <!ATTLIST biosset default (yes|no) "no">
        <!ELEMENT rom EMPTY>
        <!ATTLIST rom name CDATA #REQUIRED>
        <!ATTLIST rom bios CDATA #IMPLIED>
        <!ATTLIST rom size CDATA #REQUIRED>
        <!ATTLIST rom crc CDATA #IMPLIED>
        <!ATTLIST rom sha1 CDATA #IMPLIED>
        <!ATTLIST rom merge CDATA #IMPLIED>
        <!ATTLIST rom region CDATA #IMPLIED>
        <!ATTLIST rom offset CDATA #IMPLIED>
        <!ATTLIST rom status (baddump|nodump|good) "good">
        <!ATTLIST rom optional (yes|no) "no">
        <!ELEMENT disk EMPTY>
        <!ATTLIST disk name CDATA #REQUIRED>
        <!ATTLIST disk sha1 CDATA #IMPLIED>
        <!ATTLIST disk merge CDATA #IMPLIED>
        <!ATTLIST disk region CDATA #IMPLIED>
        <!ATTLIST disk index CDATA #IMPLIED>
        <!ATTLIST disk writable (yes|no) "no">
        <!ATTLIST disk status (baddump|nodump|good) "good">
        <!ATTLIST disk optional (yes|no) "no">
        <!ELEMENT device_ref EMPTY>
        <!ATTLIST device_ref name CDATA #REQUIRED>
        <!ELEMENT sample EMPTY>
        <!ATTLIST sample name CDATA #REQUIRED>
        <!ELEMENT chip EMPTY>
        <!ATTLIST chip name CDATA #REQUIRED>
        <!ATTLIST chip tag CDATA #IMPLIED>
        <!ATTLIST chip type (cpu|audio) #REQUIRED>
        <!ATTLIST chip clock CDATA #IMPLIED>
        <!ELEMENT display EMPTY>
        <!ATTLIST display tag CDATA #IMPLIED>
        <!ATTLIST display type (raster|vector|lcd|unknown) #REQUIRED>
        <!ATTLIST display rotate (0|90|180|270) #IMPLIED>
        <!ATTLIST display flipx (yes|no) "no">
        <!ATTLIST display width CDATA #IMPLIED>
        <!ATTLIST display height CDATA #IMPLIED>
        <!ATTLIST display refresh CDATA #REQUIRED>
        <!ATTLIST display pixclock CDATA #IMPLIED>
        <!ATTLIST display htotal CDATA #IMPLIED>
        <!ATTLIST display hbend CDATA #IMPLIED>
        <!ATTLIST display hbstart CDATA #IMPLIED>
        <!ATTLIST display vtotal CDATA #IMPLIED>
        <!ATTLIST display vbend CDATA #IMPLIED>
        <!ATTLIST display vbstart CDATA #IMPLIED>
        <!ELEMENT sound EMPTY>
        <!ATTLIST sound channels CDATA #REQUIRED>
        <!ELEMENT input (control*)>
        <!ATTLIST input service (yes|no) "no">
        <!ATTLIST input tilt (yes|no) "no">
        <!ATTLIST input players CDATA #REQUIRED>
        <!ATTLIST input coins CDATA #IMPLIED>
        <!ELEMENT control EMPTY>
        <!ATTLIST control type CDATA #REQUIRED>
        <!ATTLIST control player CDATA #IMPLIED>
        <!ATTLIST control buttons CDATA #IMPLIED>
        <!ATTLIST control reqbuttons CDATA #IMPLIED>
        <!ATTLIST control minimum CDATA #IMPLIED>
        <!ATTLIST control maximum CDATA #IMPLIED>
        <!ATTLIST control sensitivity CDATA #IMPLIED>
        <!ATTLIST control keydelta CDATA #IMPLIED>
        <!ATTLIST control reverse (yes|no) "no">
        <!ATTLIST control ways CDATA #IMPLIED>
        <!ATTLIST control ways2 CDATA #IMPLIED>
        <!ATTLIST control ways3 CDATA #IMPLIED>
        <!ELEMENT dipswitch (dipvalue*)>
        <!ATTLIST dipswitch name CDATA #REQUIRED>
        <!ATTLIST dipswitch tag CDATA #REQUIRED>
        <!ATTLIST dipswitch mask CDATA #REQUIRED>
        <!ELEMENT dipvalue EMPTY>
        <!ATTLIST dipvalue name CDATA #REQUIRED>
        <!ATTLIST dipvalue value CDATA #REQUIRED>
        <!ATTLIST dipvalue default (yes|no) "no">
        <!ELEMENT configuration (confsetting*)>
        <!ATTLIST configuration name CDATA #REQUIRED>
        <!ATTLIST configuration tag CDATA #REQUIRED>
        <!ATTLIST configuration mask CDATA #REQUIRED>
        <!ELEMENT confsetting EMPTY>
        <!ATTLIST confsetting name CDATA #REQUIRED>
        <!ATTLIST confsetting value CDATA #REQUIRED>
        <!ATTLIST confsetting default (yes|no) "no">
        <!ELEMENT port (analog*)>
        <!ATTLIST port tag CDATA #REQUIRED>
        <!ELEMENT analog EMPTY>
        <!ATTLIST analog mask CDATA #REQUIRED>
        <!ELEMENT adjuster EMPTY>
        <!ATTLIST adjuster name CDATA #REQUIRED>
        <!ATTLIST adjuster default CDATA #REQUIRED>
        <!ELEMENT driver EMPTY>
        <!ATTLIST driver status (good|imperfect|preliminary) #REQUIRED>
        <!ATTLIST driver emulation (good|imperfect|preliminary) #REQUIRED>
        <!ATTLIST driver color (good|imperfect|preliminary) #REQUIRED>
        <!ATTLIST driver sound (good|imperfect|preliminary) #REQUIRED>
        <!ATTLIST driver graphic (good|imperfect|preliminary) #REQUIRED>
        <!ATTLIST driver cocktail (good|imperfect|preliminary) #IMPLIED>
        <!ATTLIST driver protection (good|imperfect|preliminary) #IMPLIED>
        <!ATTLIST driver savestate (supported|unsupported) #REQUIRED>
        <!ELEMENT device (instance*, extension*)>
        <!ATTLIST device type CDATA #REQUIRED>
        <!ATTLIST device tag CDATA #IMPLIED>
        <!ATTLIST device fixed_image CDATA #IMPLIED>
        <!ATTLIST device mandatory CDATA #IMPLIED>
        <!ATTLIST device interface CDATA #IMPLIED>
        <!ELEMENT instance EMPTY>
        <!ATTLIST instance name CDATA #REQUIRED>
        <!ATTLIST instance briefname CDATA #REQUIRED>
        <!ELEMENT extension EMPTY>
        <!ATTLIST extension name CDATA #REQUIRED>
        <!ELEMENT slot (slotoption*)>
        <!ATTLIST slot name CDATA #REQUIRED>
        <!ELEMENT slotoption EMPTY>
        <!ATTLIST slotoption name CDATA #REQUIRED>
        <!ATTLIST slotoption devname CDATA #REQUIRED>
        <!ATTLIST slotoption default (yes|no) "no">
        <!ELEMENT softwarelist EMPTY>
        <!ATTLIST softwarelist name CDATA #REQUIRED>
        <!ATTLIST softwarelist status (original|compatible) #REQUIRED>
        <!ATTLIST softwarelist filter CDATA #IMPLIED>
        <!ELEMENT ramoption (#PCDATA)>
        <!ATTLIST ramoption default CDATA #IMPLIED>
        ]>

<mame build="0.186 (mame0186)" mameconfig="10">
    <machine name="005" sourcefile="segag80r.cpp" sampleof="005">
        <description>005</description>
        <year>1981</year>
        <manufacturer>Sega</manufacturer>
        <biosset name="biosset 01" description="biosset 001"/>
        <rom name="1346b.cpu-u25" size="2048" crc="8e68533e" sha1="a257c556d31691068ed5c991f1fb2b51da4826db"
             region="maincpu" offset="0"/>
        <disk name="disk 01" region="maincpu" status="nodump" optional="yes" writable="no"/>
        <device_ref name="z80"/>
        <sample name="lexplode"/>
        <chip type="cpu" tag="maincpu" name="Z80" clock="3867000"/>
        <display tag="screen" type="raster" rotate="270" width="256" height="224" refresh="59.998138" pixclock="5156000"
                 htotal="328" hbend="0" hbstart="256" vtotal="262" vbend="0" vbstart="224"/>
        <sound channels="1"/>
        <input players="2" coins="2" service="yes">
            <control type="joy" player="1" buttons="1" ways="4"/>
        </input>
        <dipswitch name="Coin A" tag="D1D0" mask="15">
            <dipvalue name="4 Coins/1 Credit" value="0"/>
        </dipswitch>
        <configuration name="Treat Joystick as..." tag="CONFIG" mask="1">
            <confsetting name="Buttons" value="0" default="yes"/>
        </configuration>
        <port tag=":D1D0">
            <analog mask="1"/>
        </port>
        <adjuster name="VR2 - DAC Volume" default="90"/>
        <driver status="imperfect" emulation="good" color="good" sound="imperfect" graphic="good"
                savestate="unsupported"/>
        <device type="cassette" tag="cassette">
            <instance name="cassette" briefname="cass"/>
            <extension name="wav"/>
        </device>
    </machine>
</mame>